# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/drunkeneye/code/cedar/cedar.shark

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/drunkeneye/code/cedar/cedar.shark

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/drunkeneye/code/cedar/cedar.shark/CMakeFiles /home/drunkeneye/code/cedar/cedar.shark/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/drunkeneye/code/cedar/cedar.shark/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cShark

# Build rule for target.
cShark: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cShark
.PHONY : cShark

# fast build rule for target.
cShark/fast:
	$(MAKE) -f CMakeFiles/cShark.dir/build.make CMakeFiles/cShark.dir/build
.PHONY : cShark/fast

cShark/Camera.o: cShark/Camera.cpp.o
.PHONY : cShark/Camera.o

# target to build an object file
cShark/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/cShark.dir/build.make CMakeFiles/cShark.dir/cShark/Camera.cpp.o
.PHONY : cShark/Camera.cpp.o

cShark/Camera.i: cShark/Camera.cpp.i
.PHONY : cShark/Camera.i

# target to preprocess a source file
cShark/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/cShark.dir/build.make CMakeFiles/cShark.dir/cShark/Camera.cpp.i
.PHONY : cShark/Camera.cpp.i

cShark/Camera.s: cShark/Camera.cpp.s
.PHONY : cShark/Camera.s

# target to generate assembly for a file
cShark/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/cShark.dir/build.make CMakeFiles/cShark.dir/cShark/Camera.cpp.s
.PHONY : cShark/Camera.cpp.s

cShark/SimpleSummation.o: cShark/SimpleSummation.cpp.o
.PHONY : cShark/SimpleSummation.o

# target to build an object file
cShark/SimpleSummation.cpp.o:
	$(MAKE) -f CMakeFiles/cShark.dir/build.make CMakeFiles/cShark.dir/cShark/SimpleSummation.cpp.o
.PHONY : cShark/SimpleSummation.cpp.o

cShark/SimpleSummation.i: cShark/SimpleSummation.cpp.i
.PHONY : cShark/SimpleSummation.i

# target to preprocess a source file
cShark/SimpleSummation.cpp.i:
	$(MAKE) -f CMakeFiles/cShark.dir/build.make CMakeFiles/cShark.dir/cShark/SimpleSummation.cpp.i
.PHONY : cShark/SimpleSummation.cpp.i

cShark/SimpleSummation.s: cShark/SimpleSummation.cpp.s
.PHONY : cShark/SimpleSummation.s

# target to generate assembly for a file
cShark/SimpleSummation.cpp.s:
	$(MAKE) -f CMakeFiles/cShark.dir/build.make CMakeFiles/cShark.dir/cShark/SimpleSummation.cpp.s
.PHONY : cShark/SimpleSummation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... cShark"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cShark/Camera.o"
	@echo "... cShark/Camera.i"
	@echo "... cShark/Camera.s"
	@echo "... cShark/SimpleSummation.o"
	@echo "... cShark/SimpleSummation.i"
	@echo "... cShark/SimpleSummation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

